package org.mypackage.yuqar.hibernate;
// Generated 12 Feb 2016 2:02:15 PM by Hibernate Tools 4.3.1



/**
 * Log generated by hbm2java
 */
public class Log  implements java.io.Serializable {


     private LogId id;
     private String success;
     private String page;
     private String comments;
     private String location;
     private String ipAddress;
     private String datee;

    public Log() {
    }

	
    public Log(LogId id) {
        this.id = id;
    }
    public Log(LogId id, String success, String page, String comments, String location, String ipAddress, String datee) {
       this.id = id;
       this.success = success;
       this.page = page;
       this.comments = comments;
       this.location = location;
       this.ipAddress = ipAddress;
       this.datee = datee;
    }
   
    public LogId getId() {
        return this.id;
    }
    
    public void setId(LogId id) {
        this.id = id;
    }
    public String getSuccess() {
        return this.success;
    }
    
    public void setSuccess(String success) {
        this.success = success;
    }
    public String getPage() {
        return this.page;
    }
    
    public void setPage(String page) {
        this.page = page;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getIpAddress() {
        return this.ipAddress;
    }
    
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    public String getDatee() {
        return this.datee;
    }
    
    public void setDatee(String datee) {
        this.datee = datee;
    }




}


