package org.mypackage.yuqar.hibernate;
// Generated 12 Feb 2016 2:02:15 PM by Hibernate Tools 4.3.1



/**
 * LogId generated by hbm2java
 */
public class LogId  implements java.io.Serializable {


     private String username;
     private String passsword;
     private String email;

    public LogId() {
    }

    public LogId(String username, String passsword, String email) {
       this.username = username;
       this.passsword = passsword;
       this.email = email;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPasssword() {
        return this.passsword;
    }
    
    public void setPasssword(String passsword) {
        this.passsword = passsword;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


