package org.mypackage.yuqar.hibernate;
// Generated 12 Feb 2016 2:02:15 PM by Hibernate Tools 4.3.1



/**
 * Logon generated by hbm2java
 */
public class Logon  implements java.io.Serializable {


     private LogonId id;
     private String registeredDate;

    public Logon() {
    }

	
    public Logon(LogonId id) {
        this.id = id;
    }
    public Logon(LogonId id, String registeredDate) {
       this.id = id;
       this.registeredDate = registeredDate;
    }
   
    public LogonId getId() {
        return this.id;
    }
    
    public void setId(LogonId id) {
        this.id = id;
    }
    public String getRegisteredDate() {
        return this.registeredDate;
    }
    
    public void setRegisteredDate(String registeredDate) {
        this.registeredDate = registeredDate;
    }




}


