package org.mypackage.yuqar.hibernate;
// Generated 12 Feb 2016 2:02:15 PM by Hibernate Tools 4.3.1



/**
 * Services generated by hbm2java
 */
public class Services  implements java.io.Serializable {


     private int sid;
     private String serviceName;

    public Services() {
    }

    public Services(int sid, String serviceName) {
       this.sid = sid;
       this.serviceName = serviceName;
    }
   
    public int getSid() {
        return this.sid;
    }
    
    public void setSid(int sid) {
        this.sid = sid;
    }
    public String getServiceName() {
        return this.serviceName;
    }
    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }




}


