package org.mypackage.yuqar.hibernate;
// Generated 12 Feb 2016 2:02:15 PM by Hibernate Tools 4.3.1



/**
 * SubServices generated by hbm2java
 */
public class SubServices  implements java.io.Serializable {


     private int ssid;
     private int sid;
     private String serviceName;

    public SubServices() {
    }

    public SubServices(int ssid, int sid, String serviceName) {
       this.ssid = ssid;
       this.sid = sid;
       this.serviceName = serviceName;
    }
   
    public int getSsid() {
        return this.ssid;
    }
    
    public void setSsid(int ssid) {
        this.ssid = ssid;
    }
    public int getSid() {
        return this.sid;
    }
    
    public void setSid(int sid) {
        this.sid = sid;
    }
    public String getServiceName() {
        return this.serviceName;
    }
    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }




}


